apiVersion: stable.example.com/v1
kind: AWSAuth
metadata:
  name: my-aws-auth
  namespace: kube-system
spec:
  mapRoles:
    - rolearn: arn:aws:iam::123456789012:role/my-role
      username: my-user
      groups:
        - system:masters
  mapUsers:
    - userarn: arn:aws:iam::123456789012:user/my-user
      username: my-user
      groups:
        - system:masters
